import '@/styles/globals.scss'
import initFirebase from '@/_services/firebase/initFirebase'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  initFirebase()
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
